name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: xtoke
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and test with Maven
        run: mvn clean package jacoco:report --fail-at-end

      - name: Verify JAR generation
        run: |
          echo "Listing files in target directory:"
          ls -l target
          JAR_FILE=$(ls target/*.jar 2>/dev/null)
          if [ -z "$JAR_FILE" ]; then
            echo "JAR file not found!" && exit 1
          fi

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: controle-estoque-jar
          path: target/controle-estoque*.jar

  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Download JAR from artifact
        uses: actions/download-artifact@v4
        with:
          name: controle-estoque-jar
          path: target

      - name: List files in project root
        run: ls -R .

      - name: Build Docker Image
        run: docker build -t controle-estoque .

      - name: Push Docker Image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker tag controle-estoque:latest ${{ secrets.DOCKER_USERNAME }}/controle-estoque:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/controle-estoque:latest
   
       
#  deploy:
#    runs-on: ubuntu-latest
#    needs: docker
#
#    steps:
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v2
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: us-east-1
#
#      - name: Update ECS Service
#        run: |
#          aws ecs update-service --cluster nava-log-cluster --service nava-log-service --force-new-deployment
          
